### ISSUE TITLE
installing on ubuntu

### ISSUE THREAD

**Issue by kehiy** [liara-cloud/liara-cli#122]
hello liara team

I'm trying to run `liara --version` command in ubuntu, but this is the result:
```bash
(node:438330) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/@liara/cli/node_modules/@oclif/core/lib/command.js:45
            delete this.baseFlags?.json;
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@liara/cli/node_modules/@oclif/core/lib/index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
(node:438330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:438330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mhemrg** [comment]
Hi @kehiy,
You need to upgrade your NodeJS version to Node 18.

You can check your current version using `node -v`.

**Comment by kehiy** [comment]
@mhemrg thanks
