### ISSUE TITLE
liara shell error

### ISSUE THREAD

**Issue by mhemrg** [liara-cloud/liara-cli#38]
I just pressed ctrl + c when I was using `liara shell` and got the following error:

```
root@c7fbcafa695b:/app# e^C
root@c7fbcafa695b:/app# exit
exit
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/Users/mhe/n/lib/node_modules/@liara/cli/node_modules/ws/lib/websocket.js:1015:17)
    at WebSocket.send (/Users/mhe/n/lib/node_modules/@liara/cli/node_modules/ws/lib/websocket.js:451:7)
    at Duplex.duplex._write (/Users/mhe/n/lib/node_modules/@liara/cli/node_modules/ws/lib/stream.js:151:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Duplex.Writable.write (internal/streams/writable.js:303:10)
    at ReadStream.ondata (internal/streams/readable.js:726:22)
    at ReadStream.emit (events.js:387:35)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:261:11)
    at ReadStream.Readable.push (internal/streams/readable.js:204:10)
Emitted 'error' event on Duplex instance at:
    at Duplex.duplexOnError (/Users/mhe/n/lib/node_modules/@liara/cli/node_modules/ws/lib/stream.js:37:10)
    at Duplex.emit (events.js:387:35)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at errorOrDestroy (internal/streams/destroy.js:168:7)
    at onwriteError (internal/streams/writable.js:391:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by mhemrg** [comment]
Cannot reproduce.
